%% Train and Validate Surrogate Model for Braking Sensor
%
% <<Mining_Loader_Train_Surrogate_Overview.png>>
%

%% Overview
% This example trains an AI surrogate model from data generated by a
% mining loader model created in Simscape. Machine Learning is used for
% both the models and model training.  The basic steps are:
%
% # *Prepare the data* collected from a DoE for training and validation
% # *Select the models* that will be trained
% # *Train the models* using a portion of the DoE data
% # *Evaluate the accuracy* of all trained models using validation data
% # *Select the model* for use in other steps of the design workflow
%
% The code used to create this documentation is here: <matlab:edit('vrt_brk_train_surrogate.m'); vrt_brk_train_surrogate.m>
%
% (<matlab:web('Mining_Loader_Design_Overview.html') return to Mining Loader Design with Simscape Overview>)
%
% Copyright 2023-2026 The MathWorks, Inc.

%% Load and Analyze the Training Data
%
% Load results of DoE that generated training data. The scatter plots show
% the distribution of parameter values and resulting braking distance,
% which gives a slight indication of the influence of the parameters on
% performance metric.

load("FullResultsTable.mat");

% Plot matrix of scatter plots
figure;
[~,ax,bigax] = gplotmatrix(FullResultsTable{:,:},[],[],[],[],[],[],[],...
    FullResultsTable.Properties.VariableNames, FullResultsTable.Properties.VariableNames);
title(['Scatter Plot of ' num2str(height(FullResultsTable)) ' Samples for ' num2str(width(FullResultsTable)-1) ' Parameters.'],'FontSize',18)

set(gcf,'Position',[54   255   850   706])
for j = 1:size(ax,1)
    for k = 1:size(ax,2)
        %ax(j,k).XLabel.String = '';
        %ax(j,k).YLabel.Interpreter = 'none';
        %ax(j,k).YLabel.Rotation = 0;        
        %ax(j,k).YTickLabel = [];
        ax(j,k).Box = 'on'; 
    end
end

%% Train Machine Learning Models
%
% Use training data to train Machine Learning models.  Both multi-output
% and single output models are trained. After the models are trained, we
% assess the accuracy of each model using the test data.  We compare the
% performance metric predicted by the trained model against the true value
% from the original Simscape simulation.  The most accurate models will be
% used for the following steps of the workflow.
%
% From the plots below, it is clear that the Gaussian Process Regression
% model is more accurate than the Regression Bagged Ensemble model.  That
% is the model that will be used for the virtual sensor

if(~exist('now_string','var'))
    now_string = 'none';
end
[bagModel, gpModel] = TrainSurrogate(FullResultsTable,now_string);

gpMdlCompact = compact(gpModel);

save gpMdlCompact gpMdlCompact

%% Mining Loader Model
%
% The virtual braking distance sensor performance must be validated by
% connecting it to the model of the mining loader. The sensor will be
% tested in the same model we used to generate the training data.
%
% <matlab:open_system('Mining_Loader_Sweep'); Open Model>

open_system('Mining_Loader_Sweep')

ann_h = find_system('Mining_Loader_Sweep','MatchFilter',@Simulink.match.allVariants,'FindAll', 'on','type','annotation','Tag','ModelFeatures');
for i = 1:length(ann_h)
    set_param(ann_h(i),'Interpreter','off')
end

temp_VisTS = minMachParams.visual.Ts;
minMachParams.visual.Ts = 0.1;

%% Vehicle Model
%
% The vehicle model contains the articulated chassis with a hinge
% connecting the chassis to the frame. The implement attaches to the frame
% Two wheels on the rear frame and two wheels on the front frame are
% connected via driveshafts to the drivetrain  Contact forces enable the
% tires to ride over the selected surface.
%
% The virtual braking distance sensor can be enabled or disabled, depending
% on the stage of model development.  It takes sensor inputs and estimates
% the braking distance.
%
% <matlab:open_system('Mining_Loader_Sweep');open_system('Mining_Loader_Sweep/Mining%20Loader/Vehicle','force');Open Subsystem>

set_param('Mining_Loader_Sweep/Mining Loader/Vehicle','LinkStatus','none')
open_system('Mining_Loader_Sweep/Mining Loader/Vehicle','force')

%% Test Surrogate Model
% 
% The surrogate model is used to estimate braking distance.  The current
% bucket load, vehicle pitch, boom angle, and vehicle speed are provided as
% inputs, and the trained Regression Gaussian Process model estimates the
% braking distance.  Variable Brick Solid blocks visualize the braking
% distance in the animation.
%
% <matlab:open_system('Mining_Loader_Sweep');open_system('Mining_Loader_Sweep/Mining%20Loader/Braking%20Distance%20Sensor/Estimate','force'); Open Subsystem>

set_param('Mining_Loader_Sweep/Mining Loader/Braking Distance Sensor/Estimate','LinkStatus','none')
open_system('Mining_Loader_Sweep/Mining Loader/Braking Distance Sensor/Estimate','force')
set_param('Mining_Loader_Sweep/Mining Loader','popup_sensor','Estimate');
set_param('Mining_Loader_Sweep', 'SimulationCommand', 'update')

%%
% A braking test is performed and the braking distance estimated by the
% sensor is compared to the final braking distance measured during
% simulation.  Though the match is close, it is not exact.  The vehicle
% pitch data is sampled as it would be on an actual sensor, and this
% slightly alters the input to the virtual braking sensor.

[extInput_Mining_Loader_Sweep, minMachParams, Init] = test_MLSweep_braking(...
    'Mining_Loader_Sweep',minMachParams,testSettings,Init,...
    12,11.31,0,25,0,14000,40);

out=sim('Mining_Loader_Sweep');
BrakingDist_est = findLoaderBrkDist_estim(out.logsout_Mining_Loader_Sweep);
sm_mining_loader_plot1whlspd(out.logsout_Mining_Loader_Sweep,minMachParams.contact.tireRad/1000,minMachParams.contact.tireRad/1000,true);
set(gcf,'Position',[54   255   850   706])
sm_mining_loader_plot2xbrkest(out.logsout_Mining_Loader_Sweep);
set(gcf,'Position',[54   255   850   706])

minMachParams.visual.Ts = temp_VisTS;

%%
%clear all
%close all
bdclose all