function [allTests,testPoints] = generateTestPoints( ...
    minMachParams, ...
    numBoomPoints, ...
    numVehSpeedPoints, ...
    numSlopePoints, ...
    numBucketLoadPoints)

%GENERATETESTPOINTS Generate parameter sweep combinations.
%
% Inputs
%   minMachParams         Vehicle parameter structure
%   numBoomPoints         Number of boom angle points
%   numVehSpeedPoints     Number of vehicle speed points
%   numSlopePoints        Number of slope points
%   numBucketLoadPoints   Number of bucket load points
%
% Outputs
%   allTests              Table containing all parameter combinations
%   testPoints            Structure containing individual sweep vectors

%% Boom Lift
testPoints.numBoomPoints = numBoomPoints;
testPoints.boomAngleAll = linspace( ...
    0, ...
    minMachParams.boomLift.maxAngle, ...
    numBoomPoints)';

%% Vehicle Speed
testPoints.numVehSpeedPoints = numVehSpeedPoints;
testPoints.vehicleSpeedAll = linspace( ...
    minMachParams.maxVehSpeed.reverse, ...
    minMachParams.maxVehSpeed.forward, ...
    numVehSpeedPoints)';

%% Terrain Slope
testPoints.numSlopePoints = numSlopePoints;
testPoints.slopeAll = linspace( ...
    minMachParams.terrain.minSlope, ...
    minMachParams.terrain.maxSlope, ...
    numSlopePoints)';

%% Bucket Load
testPoints.numBucketLoadPoints = numBucketLoadPoints;
testPoints.bucketLoadAll = linspace( ...
    minMachParams.bucketLoad.empty, ...
    minMachParams.bucketLoad.full, ...
    numBucketLoadPoints)';

%% Build all combinations
allTests = combinations( ...
    testPoints.boomAngleAll, ...
    testPoints.vehicleSpeedAll, ...
    testPoints.slopeAll, ...
    testPoints.bucketLoadAll);

allTests = renamevars( ...
    allTests, ...
    ["Var1","Var2","Var3","Var4"], ...
    ["BoomAngle","VehicleSpeed","Slope","BucketLoad"]);

end